CREATE TYPE "public"."jenis_kelamin" AS ENUM('Laki-laki', 'Perempuan');--> statement-breakpoint
CREATE TYPE "public"."jenjang" AS ENUM('Paud', 'Caberawit', 'Pra Remaja', 'Remaja', 'Pra Nikah');--> statement-breakpoint
CREATE TYPE "public"."keterangan" AS ENUM('Pendatang', 'Pribumi');--> statement-breakpoint
CREATE TYPE "public"."pendidikan_terakhir" AS ENUM('PAUD', 'TK', 'SD', 'SMP', 'SMA/SMK', 'D1-D3', 'S1/D4', 'S2', 'S3');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('Super Admin', 'Admin', 'User');--> statement-breakpoint
CREATE TYPE "public"."sambung" AS ENUM('Aktif', 'Tidak Aktif');--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('Hadir', 'Izin', 'Tidak Hadir');--> statement-breakpoint
CREATE TABLE "absensi-rajawali_desa" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"nama" varchar(256)
);
--> statement-breakpoint
CREATE TABLE "absensi-rajawali_event" (
	"id" varchar PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"title" varchar(255),
	"start_date" timestamp,
	"end_date" timestamp,
	"latitude" double precision,
	"longitude" double precision,
	"description" varchar
);
--> statement-breakpoint
CREATE TABLE "absensi-rajawali_generus" (
	"id" varchar PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"nama" varchar(255),
	"jenis_kelamin" "jenis_kelamin",
	"tempat_lahir" varchar(50),
	"tanggal_lahir" date,
	"jenjang" "jenjang",
	"nomer_whatsapp" varchar(15),
	"pendidikan_terakhir" "pendidikan_terakhir",
	"nama_orang_tua" varchar(255),
	"nomer_whatsapp_orang_tua" varchar(15),
	"sambung" "sambung",
	"alamat_tempat_tinggal" varchar(255),
	"keterangan" "keterangan",
	"alamat_asal" varchar(255),
	"kelompok_id" varchar(3)
);
--> statement-breakpoint
CREATE TABLE "absensi-rajawali_kelompok" (
	"id" varchar(3) PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"nama" varchar(50),
	"desa_id" integer
);
--> statement-breakpoint
CREATE TABLE "absensi-rajawali_log" (
	"id" varchar PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"event" varchar(255),
	"description" text,
	"user_id" varchar,
	CONSTRAINT "absensi-rajawali_log_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "absensi-rajawali_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "absensi-rajawali_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "absensi-rajawali_presence" (
	"id" varchar PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"status" "status",
	"generus_id" varchar(255) NOT NULL,
	"event_id" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "absensi-rajawali_user" (
	"id" varchar PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"username" varchar(50),
	"password" varchar(255),
	"role" "role",
	CONSTRAINT "absensi-rajawali_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "absensi-rajawali_post" USING btree ("name");